env:
  CIRRUS_CLONE_DEPTH: 1
  ARCH: amd64

Tests_task:
  matrix:
    freebsd_instance:
      image_family: freebsd-12-1
    freebsd_instance:
      image_family: freebsd-11-4
  prepare_script:
  - cd tests && sh prepare.sh
  test_script:
  - cd tests && sh run.sh
